worlds:
    - '*'
updateEventStatsSum: false
lottery:
    applicableStatKeys:
        halloween_2025_halloweenghosts: 1
        halloween_2025_creeper: 2
        halloween_2025_phantome: 2
        halloween_2025_mining: 1
        halloween_2025_mobarena: 1
        halloween_2025_netherbaeume: 1
        halloween_2025_netherwarzen: 1
        halloween_2025_schreitereiter: 1
statsDisplays: {}